### ISSUE TITLE
TEST: CircleCi cache permissions fail

### ISSUE THREAD

**Issue by ionescu77** [selfpower-ngo/selfpower.ro#21]
https://github.com/selfpower-ngo/selfpower.ro/blob/e8a78392b2f675f77ffcfad2d4a1d3d16c40d361/.circleci/config.yml#L29

<img width="947" alt="Screenshot 2020-07-07 at 15 13 03" src="https://user-images.githubusercontent.com/8016748/86779707-86db4100-c064-11ea-989a-c2089c19bd04.png">

**Comment by ionescu77** [comment]
As incerca:
```bash
run: sudo chown -R circleci:circleci /usr/local/lib/python3.*/site-packages 
```

**Comment by ionescu77** [comment]
Trebuie verificat tot fisierul `.circleci/config.yml` sa aiba python 3.7.7

https://circleci.com/docs/2.0/circleci-images/#python

https://circleci.com/docs/2.0/docker-image-tags.json

**Comment by Dominiq97** [comment]
**Master** este serverul de productie (python 3.6, etc. asa cum apare pe selfpower.ro)
Tags si tot ce facem se lucreaza pe **develop**.
In master  fisierul .circleci/config.yml e gresit:
linia 9:  
`python 3.6.7`
linia 39:
`python3.6`
In develop  fisierul .circleci/config.yml e corect astfel:
linia 9 
`python 3.7.7`
linia 39
`python3.7`

Se lucreaza pe **develop**.
`upgrade-tags` branch <- from master
commit link solved
https://github.com/selfpower-ngo/selfpower.ro/pull/20/commits/b6248c48a61b4342bcb821e145b6613b82eb1789
