### ISSUE TITLE
TAG: Consistenta in interfata la afisarea posturilor pt tag

### ISSUE THREAD

**Issue by ionescu77** [selfpower-ngo/selfpower.ro#26]
## Cand fac click pe **blog**

<img width="717" alt="Screenshot 2020-08-18 at 13 47 22" src="https://user-images.githubusercontent.com/8016748/90504329-9668a200-e159-11ea-8e55-05afa8e888e2.png">

## Dupa ce fac click pe tag

<img width="777" alt="Screenshot 2020-08-18 at 13 47 32" src="https://user-images.githubusercontent.com/8016748/90504357-9ec0dd00-e159-11ea-9833-21df1eb48d15.png">

**Comment by ionescu77** [comment]
## As dori
ceva in genul acesta. Sa fie clar unde sunt (era si inainte, dar prea sunt raspundite tag-urile si sus intre cele doua linii de la ARTICOLE SELFPOWER si sub linie.

<img width="777" alt="Screenshot 2020-08-18 at 13 47 32" src="https://user-images.githubusercontent.com/8016748/90504661-1262ea00-e15a-11ea-9880-4dfa1097414b.png">

**Comment by Dominiq97** [comment]
![image](https://user-images.githubusercontent.com/37049614/90506019-4b03c300-e15c-11ea-9b66-25b7e5d8e2f1.png)
<hr>
Iar la un click pe un hashTAG apar la search elementele de tag cu urrmatorul format ca header :

![Capture](https://user-images.githubusercontent.com/37049614/90512329-ae92ee00-e166-11ea-9c60-22d2494b314d.PNG)
