### ISSUE TITLE
(for Windows users) ERROR activate.bat edit

### ISSUE THREAD

**Issue by Dominiq97** [selfpower-ngo/selfpower.ro#6]
In activate.bat which is used by python in virtual env. selfpower:<br>
```
selfpower/Scripts/activate.bat 
```
the additional instructions from README.md has to be in the following format:
 
```
set "SECRET_KEY=blbabb32wdfiwjwrs"
set "DJANGO_SETTINGS_MODULE=SelfpowerProject.settings.local"

set "MAILCHIMP_API=--hidden--"
set "MAILCHIMP_LIST_ID=--hidden--"

set "EMAIL_HOST_USER=webmaster@selfpower.ro"
set "EMAIL_HOST_PASSWORD=--hidden--"

set "GOOGLE_RECAPTCHA_SECRET_KEY=--hidden--"
set "GOOGLE_RECAPTCHA_SECRET_SERVER_KEY=--hidden--"

set "STAGING_DATABASE_PASSWORD=--hidden--"
```

https://stackoverflow.com/questions/56026422/how-to-start-python-virtual-environment-in-bat-batch-file#comment98696841_56026422

In addition to the answer already provided, you should use 
```
CD /D "C:\py\project" 
Set "env1=val1" 
Set "env2=val2" 
Set "FLASK_APP=some.py" 
```
too.

**Comment by ionescu77** [comment]
Multumesc mult. F detaliat.
Te rog pune tu in README.md

**Comment by Dominiq97** [comment]
Pus in readme ca 3.1 (continuare la pasul 3) - for windows users
